# Site settings é…ç½®ç«™ç‚¹
title: 'WeğŸ§Rogue'
description: 'ğŸ§'
keywords: 'rogue, music'
url: 'https://www.werogue.com' # your host

# nav ä¸­æ–‡å­—ç¬¦ç©ºæ ¼ï¼š&emsp;
nav: # æœ€ä½³ä½“éªŒ å…­ä¸ªæ ‡ç­¾ ä¸”æœ€å¥½æ¯ä¸ªæ ‡ç­¾ä¸è¶…è¿‡4ä¸­æ–‡å­—
  ğŸ§: '/'
  Tags: '/tags.html'
  Time Line: '/time_line.html'
  Remember me: '/remember_me.html'
  Apples: '/apples.html'

# åšä¸»
author: true
name: 'Danyow'
NickName: 'danyow'
webtitle: 'We Rogue'
bio: 'ğŸ§'
about: true
aboutyou: ''
portraits: '/assets/profile.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:i.zuucol@gmail.com'
  weixin: '../assets/qrcode.wechat.png' # ä½ çš„å¾®ä¿¡äºŒç»´ç å­˜æ”¾çš„åœ°å€
  github: 'https://github.com/danyow'
  weibo: 'https://weibo.com/u/2190813887'
  instagram: 'https://www.instagram.com/danyowed'
  Twitter: 'https://twitter.com/danyowed'
  zhihu: 'https://www.zhihu.com/people/danyowed'
  # qq: '' # ä½ çš„qqäºŒç»´ç å­˜æ”¾çš„åœ°å€ or http://wpa.qq.com/msgrd?v=3&uin='ä½ çš„QQå·'&site=qq&menu=yes
  # Codepen: ''
  # Dribbble: ''
  # Facebook: ''
  # Google: ''
  # juejin: ''
  # twitch: ''

# åˆ†é¡µ
paginate: 3
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# ä»£ç é«˜äº® ä½¿ç”¨rouge
highlighter: rouge
# ä»£ç é«˜äº®ä¸»é¢˜ä½¿ç”¨pygmentsä¸»é¢˜: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango ä»»é€‰ä¸€ä¸ªä½ å–œæ¬¢çš„ä¸»é¢˜åç§°å¡«åœ¨ä¸‹é¢çš„å•å¼•å·ä¸­
pygmentsTheme: 'default'

# å‹æƒ…é“¾æ¥
friends:
  jekyllğŸ…¹: 'https://www.jekyll.com.cn/'
  DanyowğŸ“’: 'https://www.danyow.cn/'
  HardCandy-JekyllğŸ¬: 'https://github.com/xukimseven/HardCandy-Jekyll/'

# è¯„è®º æœ€ä½³ä½“éªŒ åœ¨disqusã€livereå’ŒGitmentä¹‹é—´ä¸‰é€‰ä¸€
# disqus è¯„è®º
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# æ¥å¿…åŠ›è¯„è®º
livere: false
livere_uid: ''
# Gitmentè¯„è®º OAuth Application
Gitment: true
# Gitalkè¯„è®º OAuth Application
Gitalk: false
# gitè¯„è®ºç›¸å…³
Github_owner: 'danyow'  # githubç”¨æˆ·å
Github_repo: 'werogue'  # githubåšå®¢å­˜æ”¾çš„ä»“åº“å
client_id: 'fd75cc92f60d49935050'  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_id
client_secret: 'c60ee2d21b758ed39eae57e0592592f35146b942'  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'qq', 'qzone']

# ç™¾åº¦ç»Ÿè®¡ åœ¨baidu-urlé‡Œå¡«å†™è‡ªå·±ç›¸å…³çš„urlä»£ç 
baidu: true
baidu-url: 'b24faa7b3b06c200499d49a031f8fc8a'
# è°·æ­Œåˆ†æ åœ¨google-IDé‡Œå¡«å†™è‡ªå·±åœ¨è°·æ­Œåˆ†æè·å¾—çš„è¿½è¸ªID
google: true
google-ID: 'G-DCWQHCZV1D'

# åšå®¢å¤´ä¿¡æ¯å¤‡é€‰é¢œè‰²ï¼ˆè¯¥éƒ¨åˆ†åœ¨ç«™ç‚¹ä¸­ä¸å……å½“ç«™ç‚¹å˜é‡ï¼Œå°†å…¶å†™åœ¨postçš„å¤´ä¿¡æ¯ä¸­ç”¨æ¥å……å½“é¡µé¢å˜é‡ï¼‰
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
